## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.7
notifications:
  email: false

matrix:
 allow_failures:
 - julia: nightly

before_script:
  - export PYTHON=""
